name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODMwMjNlYWYtZDYyMC00ZmVkLWEyMWMtMmU0MmRkNmM2ZTBiIiwidGVuYW50X2lkIjoiMzZjYmZjOGYzMmU5NGJjMWFmODJhNDI0ODNlZWE0MGJhOWJlMDg2NzE5M2ZlM2JlZTBjYjMwZDI4M2NlNGU5MiIsImludGVybmFsX3NlY3JldCI6ImU4NTU3ZmM4LWVmZjAtNDNmNy05NjU0LTYzOTFhMDViOWYzYyJ9.ohHCF-OC_V2G2nSMVFmd-CzKR39HeYeENFPmKhmZ9kQ"
JWT_SECRET="ajaymandal"
